theme: jekyll-theme-cayman
markdown: kramdown
title: PiWebcam
description: Turn a Raspberry Pi into a fully-featured and dummy-proof webcam
show_downloads: false
google_analytics: UA-1633536-9
github:
  is_project_page: true
  zip_url: https://github.com/piwebcam/PiWebcam/releases/download/v1.2/PiWebcam_v1.2.zip
  tar_url: https://github.com/piwebcam/PiWebcam/releases/download/v1.2/PiWebcam_v1.2.zip
  repository_url: https://github.com/piwebcam/PiWebcam
  repository_name: PiWebcam
